### ISSUE TITLE
Unit test failing.

### ISSUE THREAD

**Issue by amanabt** [Balavarun5/DG_Maxwell#1]
**Where:** In the commit `0011aaf4f411560c378de7105c1d97bbfd126e4e` in the `lax_friedrichs_flux`
branch of this repository, which is the latest commit as of 2017-08-09 1430hrs.

**Issue:**
- Unit tests are failing on running `pytest`.
- The tests failing are:
    - `test_A_matrix`
    - `test_volume_integral_flux`
    

**Expected:** All the unit tests should be successful after each commit and if there is some problem
then it should be mentioned in the commit message.

**Comment by Balavarun5** [comment]
Unit tests are passing by setting wave speed = 1 for each test
